apiVersion: v1
kind: Service
metadata:
  name: vuln-benchmark
  namespace: vuln-benchmark
spec:
  selector:
    app: vuln-benchmark
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
