name: Notify on Dependabot PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Fail if webhook is missing
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "DISCORD_WEBHOOK_URL is not set"; exit 1;
          fi

      - name: Notify Discord
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
          --data-raw '{
          "embeds": [{
            "title": "📦 Dependabot PR Created",
            "color": 5814783
          }]
          }'
