name: CI – Build & Push Image Only

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Image to Container Registry
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: devsecopscontainer/vuln-benchmark

  trivy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image to check
        run: |
          docker build -t devsecopscontainer/vuln-benchmark:latest .
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          version: latest
      - name: Scan image
        run: |
          trivy image --severity HIGH,CRITICAL --format json --output trivy_output.json registry.digitalocean.com/devsecopscontainer/vuln-benchmark:latest
      - name: Upload Trivy report to AI Analyzer
        run: |
          curl -X POST http://139.59.206.211/analyze \
            -H "Content-Type: application/json" \
            --data-binary @trivy-report.json
